services:
  postgres:
    image: postgres:17-alpine
    container_name: privateclouddrive-postgres
    environment:
      POSTGRES_DB: PrivateCloudDrive
      POSTGRES_USER: root
      POSTGRES_PASSWORD: myPassword
    ports:
      - "5432:5432"
    volumes:
      - privateclouddrive_dev_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d PrivateCloudDrive"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  privateclouddrive_dev_postgres_data:
