<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>PrivateCloudDrive</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PrivateCloudDrive.EntityFrameworkCore\PrivateCloudDrive.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\PrivateCloudDrive.HttpApi\PrivateCloudDrive.HttpApi.csproj" />
    <ProjectReference Include="..\PrivateCloudDrive.Application.Tests\PrivateCloudDrive.Application.Tests.csproj" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="10.3.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="MockFixtures\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
