<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>PrivateCloudDrive</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PrivateCloudDrive.Application\PrivateCloudDrive.Application.csproj" />
    <ProjectReference Include="..\..\src\PrivateCloudDrive.DbMigrator\PrivateCloudDrive.DbMigrator.csproj" />
    <ProjectReference Include="..\PrivateCloudDrive.Domain.Tests\PrivateCloudDrive.Domain.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

</Project>
